### ISSUE TITLE
Create a python file

### ISSUE THREAD

**Issue by JanitaRiyaz** [JanitaRiyaz/python_projects#1]
Create a python related mini project that improves your profile and coding abilities.

**Comment by IIvexII** [comment]
Take #100days coding challenge instead. It will help you to be on track. I can help you to track your progress.

**Comment by JanitaRiyaz** [comment]
> Take #100days coding challenge instead. It will help you to be on track. I can help you to track your progress.

i don't know about this..? plz provide me further details.

**Comment by IIvexII** [comment]
You can read about this challenge [here](https://www.100daysofcode.com/). 
If I conclude, you have to make commitment to yourself to code everyday for at least **1 hour**, it can be a project, new syntax, new framework or revising previous material, and then you can tweet or post on any social media platform with the hashtag #100DaysOfCode everyday for 100 days consecutive.

**Comment by JanitaRiyaz** [comment]
Thankyou so much.. i just checked out it and it seems really benificial. Thnx for always helping me.🙂..
